# overview: https://github.com/GoogleContainerTools/skaffold
# skaffold.yml: https://skaffold.dev/docs/references/yaml/
---
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: skillset-visualizer
build:
# local(ローカルでビルド) or googleCloudBuild(CloudBuild上でビルド)
#  local:
#    useBuildkit: true
  googleCloudBuild:
    projectId: work1111
  artifacts:
  - image: us.gcr.io/work1111/sv-api
    context: .
    docker:
      dockerfile: deployments/dockerfiles/api/Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/kubernetes/pod.yml
