steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/sv-app', '-f', 'deployments/dockerfiles/app/Dockerfile', '.' ]
images:
- 'us.gcr.io/$PROJECT_ID/sv-app'